### PR TITLE
Using UrlBuilder in SFSClientImpl

### LINKED ISSUE #99: Product names with line breaks
Got a `Result code: ConnectionUnexpectedError. Message: URL rejected: Malformed input to a URL function` from the tool when trying to use a product with a line break in the middle. Maybe we can validate this earlier.

### PR DESCRIPTION
**Pull request by arthuraraujo-msft**
Closes #99

- Adds a derived SFSUrlBuilder that replaces SFSUrlComponents
  - Encoding for accountId is not needed as the hostname will fail validation from curl URL interface
  - Encoding for instanceId, namespace, product and version still has to be done at an argument level since they may be coming with forward slashes that won't be escaped when setting a URL path.
  - Has alternatives for accountId and for customUrl
- Adds tests

### CODE REVIEW

File: client/src/details/SFSClientImpl.h [hunk 1]
```diff
@@ -97,9 +98,9 @@ class SFSClientImpl : public SFSClientInterface
     void SetCustomBaseUrl(std::string customBaseUrl);
 
     /**
-     * @return The URL for the SFS service based on the parameters passed to the constructor
+     * @return A SFSUrlBuilder object that can be used to build URLs for the SFS service
      */
-    std::string GetBaseUrl() const;
+    std::unique_ptr<SFSUrlBuilder> MakeUrlBuilder() const;
```
Comment (shishirb-MSFT) [inline client/src/details/SFSClientImpl.h:103]: SFSUrlBuilder is non-copyable but you should be able to return-by-value here due to return value optimization (RVO). Did you try it?

File: client/src/details/SFSClientImpl.cpp [hunk 2]
```diff
@@ -401,18 +397,18 @@ void SFSClientImpl<ConnectionManagerT>::SetCustomBaseUrl(std::string customBaseU
...
+std::unique_ptr<SFSUrlBuilder> SFSClientImpl<ConnectionManagerT>::MakeUrlBuilder() const
 {
     if (auto envVar = test::GetTestOverride(test::TestOverride::BaseUrl))
     {
-        return *envVar;
+        return SFSUrlBuilder::CreateFromCustomUrl(*envVar, m_instanceId, m_nameSpace, m_reportingHandler);
     }
-
-    if (m_customBaseUrl)
+    else if (m_customBaseUrl)
```
Comment (shishirb-MSFT) [inline client/src/details/SFSClientImpl.cpp:406]: Why change to `else if (m_customBaseUrl)` when the if block above is still doing an unconditional return from within?

File: client/src/details/SFSUrlBuilder.cpp [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+std::string SFSUrlBuilder::GetLatestVersionBatchUrl()
+{
+    SetPath(GetNamesUrlPath());
+    SetQuery("action=BatchUpdates");
+    return GetUrl();
+}
+
+std::string SFSUrlBuilder::GetSpecificVersionUrl(const std::string& product, const std::string& version)
+{
+    SetPath(GetVersionsUrlPath(product) + EscapeString(version));
```
Comment (shishirb-MSFT) [inline client/src/details/SFSUrlBuilder.cpp:57]: Why not add an AppendPath method to UrlBuilder and use that to build the path? Will that also allow you to let curl do the url escaping?

This is more readable IMO, especially for more complex ones like in `GetNamesUrlPath`:
`SetPath(GetVersionsUrlPath(product), true /*encode*/);`
`AppendPath(version, true /*encode*/);`
`AppendPath(files, true /*encode*/);`

File: client/src/details/SFSClientImpl.h (hunk 1 above)
Comment (arthuraraujo-msft) [reply client/src/details/SFSClientImpl.h:103]: The issue was in SFSUrlBuilder::CreateFromAccountId() and SFSUrlBuilder::CreateFromCustomUrl().
I couldn't return by value there because NRVO was not allowed since SFSUrlBuilder is non-copyable

```
SFSUrlBuilder CreateFromAccountId(...)
{
    SFSUrlBuilder builder(std::move(instanceId), std::move(nameSpace), handler);
    builder.SetScheme(Scheme::Https);
    builder.SetHost(accountId + "." + std::string(c_apiDomain));
    return builder;
}
```

But it seems that creating a private constructor and switching that to below works

```
SFSUrlBuilder CreateFromAccountId(...)
{
    return SFSUrlBuilder(accountId, std::move(instanceId), std::move(nameSpace), handler);
}
```

I had to create two factories because the arguments are the same types and the constructors wouldn't be distinguishable. Another way to handle this is to create a fake type only to differentiate the constructors.

File: client/src/details/SFSUrlBuilder.cpp (hunk 3 above)
Comment (arthuraraujo-msft) [reply client/src/details/SFSUrlBuilder.cpp:57]: Curl doesn't have a facility for this, but we can implement a custom one

File: client/src/details/SFSClientImpl.h (hunk 1 above)
Comment (arthuraraujo-msft) [reply client/src/details/SFSClientImpl.h]: Create a wrapper struct to facilitate this

File: client/src/details/SFSUrlBuilder.h [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+struct SFSCustomUrl
+{
+    explicit SFSCustomUrl(std::string url) : url(std::move(url))
+    {
+    }
+
+    std::string url;
+};
+
+class SFSUrlBuilder : private UrlBuilder
```
Comment (JeffMill) [inline client/src/details/SFSUrlBuilder.h:20]: OOP nit: you have an IS-A relationship here but privately deriving from UrlBuilder.  Should UrlBuilder be a class member instead?

File: client/src/details/SFSUrlBuilder.cpp [hunk 5]
```diff
@@ -0,0 +1,87 @@
...
+    return GetUrl();
+}
+
+SFSUrlBuilder& SFSUrlBuilder::ResetPathAndQuery()
+{
+    SetPath("").SetQuery("");
+    return *this;
+}
+
+SFSUrlBuilder& SFSUrlBuilder::SetNamesUrlPath()
```
Comment (JeffMill) [inline client/src/details/SFSUrlBuilder.cpp:71]: should the name of this method (or class) reflect that it's V2 API, e.g SfsV2UrlBuilder?  Think: What would change in this class if (when) we need to also support V3?

File: client/src/details/UrlBuilder.h [hunk 6]
```diff
@@ -42,46 +42,66 @@ class UrlBuilder
...
+    UrlBuilder& SetPath(const std::string& path, bool encode = false);
+
+    /**
+     * @brief Append a path to the URL
+     * @param path The path to be appended for the URL. Ex: index.html
+     * @param encode If true, the new path element will be URL encoded, including forward slashes
+     * @throws SFSException if the string is invalid
+     * @return The reference to the current object
+     */
+    UrlBuilder& AppendPath(const std::string& path, bool encode = false);
```
Comment (JeffMill) [inline client/src/details/UrlBuilder.h:73]: as I mentioned in another review, here (and SetPath), avoid bool parameters (and especially default args!) and provide explicit methods, e.g.

* SetPath
* SetPathEncoded
* AppendPath
* AppendPathEncoded

these can each be inline calls into shared methods, but i've seen too many issues with relying on a bool and someone getting it wrong (`AppendPath(path)` vs `AppendPath(path, true)`), not to mention that anytime a parameter comment needs a comment to clarify (e.g. `AppendPath(path, true /*encode*/)`), it's a code smell.

File: client/src/details/UrlBuilder.cpp [hunk 7]
```diff
@@ -23,6 +23,33 @@ using namespace SFS::details;
 
 namespace
 {
+
+struct CurlEscapedUrlString
```
Comment (JeffMill) [inline client/src/details/UrlBuilder.cpp:27]: this should probably publically derive from a std::unique_ptr with a custom deleter that calls curl_free so that way we have a reusable object for dealing with curl_free'd objects, including this one.

File: client/src/details/UrlBuilder.cpp [hunk 8]
```diff
@@ -66,42 +93,82 @@ std::string UrlBuilder::GetUrl() const
...
     unsigned flags = 0;
     if (encode)
     {
         flags |= CURLU_URLENCODE;
     }
     THROW_IF_CURL_URL_SETUP_ERROR(curl_url_set(m_handle, CURLUPART_PATH, path.c_str(), flags));
+    return *this;
+}
+
+UrlBuilder& UrlBuilder::AppendPath(const std::string& path, bool encode)
```
Comment (JeffMill) [inline client/src/details/UrlBuilder.cpp:124]: nit: inefficient?  what if we call AppendPath several times?  Each time it's calloing curl_url_get, escaping and appending?  Is it possible to keep a "raw" std::string in this class until a "final" string (e.g. via "get" accessor) is requested by caller?

File: client/tests/functional/details/CurlConnectionTests.cpp [hunk 9]
```diff
@@ -95,14 +95,11 @@ TEST("Testing CurlConnection()")
...
+    SFSUrlBuilder urlBuilder(SFSCustomUrl(server.GetBaseUrl()), c_instanceId, c_namespace, handler);
 
     SECTION("Testing CurlConnection::Get()")
     {
-        const std::string url = SFSUrlComponents::GetSpecificVersionUrl(server.GetBaseUrl(),
-                                                                        c_instanceId,
-                                                                        c_namespace,
-                                                                        c_productName,
-                                                                        c_version);
+        const std::string url = urlBuilder.GetSpecificVersionUrl(c_productName, c_version);
```
Comment (JeffMill) [inline client/tests/functional/details/CurlConnectionTests.cpp:102]: nit: when to use = `const std::string url = ...` vs. const `std::string url{ ... }`?

**Review by JeffMill — APPROVED** [review]
approved w/suggestions

File: client/src/details/SFSUrlBuilder.h (hunk 4 above)
Comment (arthuraraujo-msft) [reply client/src/details/SFSUrlBuilder.h:20]: No, most member methods are leveraged directly, this is just an extension of the other class

Comment (JeffMill) [reply client/src/details/SFSUrlBuilder.h:20]: I meant from a usage perspective not an outside perspective, e.g.

```
class Mammal {
  bool hasFur() {  }
 };
 
 class Human: private Mammal {
  ...
  };
  
  Human jeff = new Human();
  jeff.HasFur(); /* inaccessible? */
  ```

File: client/tests/functional/details/CurlConnectionTests.cpp (hunk 9 above)
Comment (JeffMill) [reply client/tests/functional/details/CurlConnectionTests.cpp:102]: it's was a question of style, not performance.

File: client/src/details/SFSUrlBuilder.cpp (hunk 5 above)
Comment (arthuraraujo-msft) [reply client/src/details/SFSUrlBuilder.cpp:71]: My thought is, at the time, we'll update all APIs to point to that new version. I don't think we should support more than one at the same time, so it'll just be a single global change

File: client/src/details/UrlBuilder.cpp (hunk 8 above)
Comment (arthuraraujo-msft) [reply client/src/details/UrlBuilder.cpp:124]: > Is it possible to keep a "raw" std::string in this class until a "final" string (e.g. via "get" accessor) is requested by caller?

That would violate the expectation that Get() is const and only returns existing data.

What we could do is keep a raw string locally that is in sync with what is in curl_url_get(CURLUPART_PATH).
That saves the repeated get call. In the end the memory consumption will be constant of two strings for URL instead of fluctuating once AppendPath ends.
Overall it would only change the performance time of the calls.

File: client/src/details/SFSUrlBuilder.cpp [hunk 10]
```diff
@@ -49,14 +49,14 @@ std::string SFSUrlBuilder::GetLatestVersionBatchUrl()
...
     return GetUrl();
 }
 
 std::string SFSUrlBuilder::GetDownloadInfoUrl(const std::string& product, const std::string& version)
 {
     SetVersionsUrlPath(product);
-    AppendPath(version, true /*encode*/);
+    AppendPathEncoded(version);
     AppendPath("files");
     SetQuery("action=GenerateDownloadInfo");
```
Comment (JeffMill) [inline client/src/details/SFSUrlBuilder.cpp:61]: I think this would be better as  `SetQuery(parameter, value)`

Both parameters are required, and an equals is required.  Splitting these avoids the need for caller to specify = each time, and makes it more obvious as to what the parameters are, plus avoids mistakes. plus, each of these (may) need escaping, but the equals doesn't, so passing in the args separately allows the SetQuery method to do all that work for the caller.

**Review by JeffMill — APPROVED** [review]
add'l comment
